---
# group_vars file for szczecin

# human readable site name
location_name: szczecin
# IP prefix for hosts in this site, if the IP of your computer would be 
# 192.168.178.39, set the variable to 192.168.178
location_subnet:
