---
# defaults file for gitserver-config
#   * additional defaults can be found in the <subrole-name>/defaults folders

# to be added to group {{ git_os_user_name }}
system_user: link

# git connections will not be done with the system user but with a dedicated git user
git_os_user_name: git

# password for the dedicated git user
# create: 
#   * create hash: ansible all -i localhost, -m debug -a "msg={{ 'my_secret_password' | password_hash('sha512') }}"
#   * encrypt hash: ansible-vault encrypt_string --vault-id git@prompt --stdin-name 'git_os_user_password_hash'
# use in play: ansible-playbook <playbook>.yml --vault-id git@prompt
git_os_user_password_hash: "{{ 'my_secret_password' | password_hash('sha512') }}"

# The dedicated git user should not be able to use the standard shell, but should be
# restricted to the git-shell. To get the path to the git shell execute 'which git-shell'
# on the host.
git_os_user_shell: /usr/bin/git-shell
# username for git commits
git_commit_user_name: link
# user email for git commits
git_commit_user_email: link@example.org
# [optional]
# private key will be deploy by w.users to /home/git/.ssh/id_rsa
#   * create private / public key pair: ssh-keygen -o
#   * make public key available on existing git machine (e.g. a backup machine)
#   * copy content of the private key file and encrypt it (see {{ git_os_user_password_hash }})
git_private_key:
# keys to authorize repo SSH access
git_authorized_keys: []
# [optional]
# git repos on an existing git machine (e.g. a backup machine)
# example:
#    - repo: ssh://link@{{ location_subnet }}.xxx/path/to/repo/ansible.git
#      dest: /home/git/repos/ansible.git
#      bare: true
git_repositories: []